services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3212:3212"
    restart: always
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=some-key-here
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    env_file:
      - ./api/.env.example
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3212/livez"]
      interval: 15s
      timeout: 6s
      retries: 3
      start_period: 20s
    volumes:
      - static:/app/static
    depends_on:
      - db
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3212
    depends_on:
      - api
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatbot_db
      MYSQL_USER: chatbot_db
      MYSQL_PASSWORD: chatbot_db
    ports:
      - "3308:3306"
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
  static:
