FROM node:20-slim AS base
WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN apt-get update && apt-get install -y --no-install-recommends curl
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY package.json pnpm-lock.yaml tsconfig.* .
ENV NODE_ENV development
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build

EXPOSE 3212
CMD [ "pnpm", "run", "start" ]
